-- ============================================================
-- Migration 064: Procurement RPCs
-- Phase 12 — Business logic for PO lifecycle
-- ============================================================
-- New RPCs:
--   1. fn_create_purchase_order(JSONB) — Create PO with lines
--   2. fn_receive_goods(JSONB) — Physical receiving (Admin/Cook)
--   3. fn_approve_po(JSONB) — Financial reconciliation (Controller)
--   4. fn_pending_deliveries() — Pending POs for /receive screen
-- ============================================================


-- ─── 1. fn_create_purchase_order ───

CREATE OR REPLACE FUNCTION public.fn_create_purchase_order(p_payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_po_id       UUID;
  v_po_number   TEXT;
  v_line        JSONB;
  v_line_count  INTEGER := 0;
  v_sort        SMALLINT := 0;
  v_unit_price  NUMERIC;
BEGIN
  -- ── 1. Validate supplier ──
  IF p_payload->>'supplier_id' IS NULL OR p_payload->>'supplier_id' = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'supplier_id is required');
  END IF;

  -- ── 2. INSERT purchase_orders (po_number auto-generated by trigger) ──
  INSERT INTO public.purchase_orders (
    supplier_id,
    expected_date,
    notes,
    created_by
  ) VALUES (
    (p_payload->>'supplier_id')::UUID,
    (p_payload->>'expected_date')::DATE,
    p_payload->>'notes',
    auth.uid()
  )
  RETURNING id, po_number INTO v_po_id, v_po_number;

  -- ── 3. INSERT po_lines ──
  IF p_payload->'lines' IS NOT NULL
     AND jsonb_array_length(p_payload->'lines') > 0 THEN
    FOR v_line IN SELECT * FROM jsonb_array_elements(p_payload->'lines')
    LOOP
      v_sort := v_sort + 1;

      -- Auto-populate unit_price from supplier_catalog if not provided
      v_unit_price := (v_line->>'unit_price_expected')::NUMERIC;

      IF v_unit_price IS NULL THEN
        SELECT sc.last_seen_price INTO v_unit_price
        FROM public.supplier_catalog sc
        WHERE sc.supplier_id = (p_payload->>'supplier_id')::UUID
          AND (
            (v_line->>'sku_id' IS NOT NULL AND sc.sku_id = (v_line->>'sku_id')::UUID)
            OR sc.nomenclature_id = (v_line->>'nomenclature_id')::UUID
          )
        ORDER BY
          CASE WHEN sc.sku_id IS NOT NULL THEN 0 ELSE 1 END,
          sc.match_count DESC
        LIMIT 1;
      END IF;

      INSERT INTO public.po_lines (
        po_id, nomenclature_id, sku_id,
        qty_ordered, unit, unit_price_expected,
        sort_order, notes
      ) VALUES (
        v_po_id,
        (v_line->>'nomenclature_id')::UUID,
        CASE WHEN v_line->>'sku_id' IS NOT NULL AND v_line->>'sku_id' <> ''
             THEN (v_line->>'sku_id')::UUID ELSE NULL END,
        COALESCE((v_line->>'qty_ordered')::NUMERIC, 1),
        COALESCE(v_line->>'unit', 'pcs'),
        v_unit_price,
        v_sort,
        v_line->>'notes'
      );

      v_line_count := v_line_count + 1;
    END LOOP;
  END IF;

  -- ── 4. Return success ──
  RETURN jsonb_build_object(
    'ok',         true,
    'po_id',      v_po_id,
    'po_number',  v_po_number,
    'line_count', v_line_count
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;

COMMENT ON FUNCTION public.fn_create_purchase_order(JSONB)
  IS 'Phase 12: Creates PO with lines. Auto-generates PO number. Auto-populates prices from supplier_catalog.';


-- ─── 2. fn_receive_goods ───

CREATE OR REPLACE FUNCTION public.fn_receive_goods(p_payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_po_id         UUID;
  v_po_status     po_status;
  v_receiving_id  UUID;
  v_line          JSONB;
  v_full_count    INTEGER := 0;
  v_issue_count   INTEGER := 0;
  v_new_status    po_status;
  v_total_ordered NUMERIC;
  v_total_fulfilled NUMERIC;
BEGIN
  -- ── 1. Validate PO ──
  v_po_id := (p_payload->>'po_id')::UUID;

  SELECT status INTO v_po_status
  FROM public.purchase_orders
  WHERE id = v_po_id;

  IF v_po_status IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'PO not found');
  END IF;

  IF v_po_status NOT IN ('submitted', 'confirmed', 'shipped', 'partially_received') THEN
    RETURN jsonb_build_object('ok', false, 'error',
      'PO status must be submitted/confirmed/shipped/partially_received, got: ' || v_po_status::TEXT);
  END IF;

  -- ── 2. INSERT receiving_records ──
  INSERT INTO public.receiving_records (
    po_id, source, received_by, notes
  ) VALUES (
    v_po_id,
    'purchase_order',
    auth.uid(),
    p_payload->>'notes'
  )
  RETURNING id INTO v_receiving_id;

  -- ── 3. INSERT receiving_lines ──
  IF p_payload->'lines' IS NOT NULL
     AND jsonb_array_length(p_payload->'lines') > 0 THEN
    FOR v_line IN SELECT * FROM jsonb_array_elements(p_payload->'lines')
    LOOP
      INSERT INTO public.receiving_lines (
        receiving_id,
        po_line_id,
        nomenclature_id,
        sku_id,
        qty_expected,
        qty_received,
        qty_rejected,
        reject_reason,
        notes
      ) VALUES (
        v_receiving_id,
        CASE WHEN v_line->>'po_line_id' IS NOT NULL AND v_line->>'po_line_id' <> ''
             THEN (v_line->>'po_line_id')::UUID ELSE NULL END,
        (v_line->>'nomenclature_id')::UUID,
        CASE WHEN v_line->>'sku_id' IS NOT NULL AND v_line->>'sku_id' <> ''
             THEN (v_line->>'sku_id')::UUID ELSE NULL END,
        COALESCE((v_line->>'qty_expected')::NUMERIC, 0),
        COALESCE((v_line->>'qty_received')::NUMERIC, 0),
        COALESCE((v_line->>'qty_rejected')::NUMERIC, 0),
        CASE WHEN v_line->>'reject_reason' IS NOT NULL AND v_line->>'reject_reason' <> ''
             THEN (v_line->>'reject_reason')::reject_reason ELSE NULL END,
        v_line->>'notes'
      );

      IF COALESCE((v_line->>'qty_rejected')::NUMERIC, 0) > 0
         OR COALESCE((v_line->>'qty_received')::NUMERIC, 0) < COALESCE((v_line->>'qty_expected')::NUMERIC, 0) THEN
        v_issue_count := v_issue_count + 1;
      ELSE
        v_full_count := v_full_count + 1;
      END IF;
    END LOOP;
  END IF;

  -- ── 4. Determine new PO status ──
  -- Aggregate ALL receiving_lines across ALL receiving_records for this PO
  SELECT
    COALESCE(SUM(pl.qty_ordered), 0),
    COALESCE(SUM(received_sum.fulfilled), 0)
  INTO v_total_ordered, v_total_fulfilled
  FROM public.po_lines pl
  LEFT JOIN (
    SELECT
      rl.po_line_id,
      SUM(rl.qty_received + rl.qty_rejected) AS fulfilled
    FROM public.receiving_lines rl
    JOIN public.receiving_records rr ON rr.id = rl.receiving_id
    WHERE rr.po_id = v_po_id
    GROUP BY rl.po_line_id
  ) received_sum ON received_sum.po_line_id = pl.id
  WHERE pl.po_id = v_po_id;

  -- If total fulfilled >= total ordered (within tolerance), mark as received
  IF v_total_fulfilled >= v_total_ordered - 0.01 THEN
    v_new_status := 'received';
  ELSE
    v_new_status := 'partially_received';
  END IF;

  UPDATE public.purchase_orders
  SET status = v_new_status, updated_at = now()
  WHERE id = v_po_id;

  -- ── 5. Return result ──
  RETURN jsonb_build_object(
    'ok',           true,
    'receiving_id', v_receiving_id,
    'full_count',   v_full_count,
    'issue_count',  v_issue_count,
    'po_status',    v_new_status::TEXT
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;

COMMENT ON FUNCTION public.fn_receive_goods(JSONB)
  IS 'Phase 12: Physical receiving by Admin/Cook. Records what arrived. Does NOT update inventory or financials. Sets PO status to received or partially_received.';


-- ─── 3. fn_approve_po ───

CREATE OR REPLACE FUNCTION public.fn_approve_po(p_payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_po_id             UUID;
  v_expense_id        UUID;
  v_supplier_id       UUID;
  v_category_code     INTEGER;
  v_sub_category_code INTEGER;
  v_line              RECORD;
  v_purchase_count    INTEGER := 0;
  v_sku_auto_count    INTEGER := 0;
  -- SKU resolution variables (same as fn_approve_receipt v10)
  v_sku_id            UUID;
  -- UoM conversion variables
  v_conv_factor       NUMERIC;
  v_final_qty         NUMERIC;
  v_final_unit_price  NUMERIC;
BEGIN
  -- ── 1. Validate PO ──
  v_po_id := (p_payload->>'po_id')::UUID;

  SELECT po.supplier_id
  INTO v_supplier_id
  FROM public.purchase_orders po
  WHERE po.id = v_po_id
    AND po.status IN ('received', 'partially_received');

  IF v_supplier_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'PO not found or not in received/partially_received status');
  END IF;

  -- ── 2. Resolve category from supplier ──
  v_category_code := (p_payload->>'category_code')::INTEGER;
  v_sub_category_code := (p_payload->>'sub_category_code')::INTEGER;

  IF v_category_code IS NULL THEN
    SELECT s.category_code, s.sub_category_code
    INTO v_category_code, v_sub_category_code
    FROM public.suppliers s WHERE s.id = v_supplier_id;
  END IF;

  IF v_category_code IS NULL THEN
    v_category_code := 2000;
  END IF;

  -- ── 3. INSERT expense_ledger (Hub) — same pattern as fn_approve_receipt ──
  INSERT INTO public.expense_ledger (
    transaction_date, flow_type, category_code, sub_category_code,
    supplier_id, po_id, details, comments, invoice_number,
    amount_original, currency, exchange_rate,
    discount_total, vat_amount, delivery_fee,
    paid_by, payment_method, status, has_tax_invoice,
    receipt_supplier_url, receipt_bank_url, tax_invoice_url
  ) VALUES (
    COALESCE((p_payload->>'transaction_date')::DATE, CURRENT_DATE),
    COALESCE(p_payload->>'flow_type', 'OpEx'),
    v_category_code,
    v_sub_category_code,
    v_supplier_id,
    v_po_id,
    COALESCE(p_payload->>'details', 'PO reconciliation'),
    p_payload->>'comments',
    p_payload->>'invoice_number',
    COALESCE((p_payload->>'amount_original')::NUMERIC, 0),
    COALESCE(p_payload->>'currency', 'THB'),
    COALESCE((p_payload->>'exchange_rate')::NUMERIC, 1),
    COALESCE((p_payload->>'discount_total')::NUMERIC, 0),
    COALESCE((p_payload->>'vat_amount')::NUMERIC, 0),
    COALESCE((p_payload->>'delivery_fee')::NUMERIC, 0),
    COALESCE(p_payload->>'paid_by', ''),
    COALESCE(p_payload->>'payment_method', 'transfer'),
    COALESCE(p_payload->>'status', 'paid'),
    COALESCE((p_payload->>'has_tax_invoice')::BOOLEAN, false),
    p_payload->>'receipt_supplier_url',
    p_payload->>'receipt_bank_url',
    p_payload->>'tax_invoice_url'
  )
  RETURNING id INTO v_expense_id;

  -- ── 4. Process receiving_lines → purchase_logs + sku_balances ──
  -- Aggregate all receiving_lines for this PO (may have multiple receiving_records)
  FOR v_line IN
    SELECT
      rl.id AS receiving_line_id,
      rl.po_line_id,
      rl.nomenclature_id,
      rl.sku_id AS line_sku_id,
      rl.qty_received,
      rl.unit_price_actual,
      pl.sku_id AS po_sku_id,
      pl.unit_price_expected,
      pl.unit
    FROM public.receiving_lines rl
    JOIN public.receiving_records rr ON rr.id = rl.receiving_id
    LEFT JOIN public.po_lines pl ON pl.id = rl.po_line_id
    WHERE rr.po_id = v_po_id
      AND rl.qty_received > 0
  LOOP
    -- ── 4a. Resolve SKU (4-strategy, same as fn_approve_receipt v10) ──
    v_sku_id := COALESCE(v_line.line_sku_id, v_line.po_sku_id);

    -- Strategy 2: via supplier_catalog
    IF v_sku_id IS NULL AND v_supplier_id IS NOT NULL THEN
      SELECT sc.sku_id INTO v_sku_id
      FROM public.supplier_catalog sc
      WHERE sc.supplier_id = v_supplier_id
        AND sc.sku_id IS NOT NULL
        AND sc.nomenclature_id = v_line.nomenclature_id
      ORDER BY sc.match_count DESC
      LIMIT 1;
    END IF;

    -- Strategy 3: first active SKU for nomenclature
    IF v_sku_id IS NULL THEN
      SELECT id INTO v_sku_id
      FROM public.sku
      WHERE nomenclature_id = v_line.nomenclature_id
        AND is_active = true
      ORDER BY created_at ASC
      LIMIT 1;
    END IF;

    -- Strategy 4: auto-create SKU
    IF v_sku_id IS NULL THEN
      INSERT INTO public.sku (
        sku_code, nomenclature_id, product_name
      ) VALUES (
        public.fn_generate_sku_code(),
        v_line.nomenclature_id,
        (SELECT name FROM public.nomenclature WHERE id = v_line.nomenclature_id)
      )
      RETURNING id INTO v_sku_id;
      v_sku_auto_count := v_sku_auto_count + 1;
    END IF;

    -- ── 4b. UoM conversion from supplier_catalog ──
    v_conv_factor := NULL;
    SELECT sc.conversion_factor
    INTO v_conv_factor
    FROM public.supplier_catalog sc
    WHERE sc.supplier_id = v_supplier_id
      AND (sc.sku_id = v_sku_id OR sc.nomenclature_id = v_line.nomenclature_id)
      AND sc.conversion_factor IS NOT NULL
    ORDER BY
      CASE WHEN sc.sku_id = v_sku_id THEN 0 ELSE 1 END,
      sc.match_count DESC
    LIMIT 1;

    -- ── 4c. Calculate final quantities ──
    IF v_conv_factor IS NOT NULL AND v_conv_factor > 0 THEN
      v_final_qty := v_line.qty_received * v_conv_factor;
    ELSE
      v_final_qty := v_line.qty_received;
    END IF;

    -- Use actual price if provided, otherwise expected
    v_final_unit_price := COALESCE(v_line.unit_price_actual, v_line.unit_price_expected, 0);

    -- Recalculate unit_price if conversion applied
    IF v_conv_factor IS NOT NULL AND v_conv_factor > 0 AND v_final_qty > 0 THEN
      v_final_unit_price := (v_line.qty_received * COALESCE(v_line.unit_price_actual, v_line.unit_price_expected, 0)) / v_final_qty;
    END IF;

    -- ── 4d. INSERT purchase_logs ──
    INSERT INTO public.purchase_logs (
      nomenclature_id, sku_id, supplier_id,
      quantity, price_per_unit, total_price,
      invoice_date, expense_id,
      po_line_id, receiving_line_id,
      notes
    ) VALUES (
      v_line.nomenclature_id,
      v_sku_id,
      v_supplier_id,
      v_final_qty,
      v_final_unit_price,
      v_final_qty * v_final_unit_price,
      COALESCE((p_payload->>'transaction_date')::DATE, CURRENT_DATE),
      v_expense_id,
      v_line.po_line_id,
      v_line.receiving_line_id,
      (SELECT name FROM public.nomenclature WHERE id = v_line.nomenclature_id)
    );

    -- ── 4e. UPSERT sku_balances ──
    INSERT INTO public.sku_balances (sku_id, nomenclature_id, quantity, last_received_at)
    VALUES (v_sku_id, v_line.nomenclature_id, v_final_qty, now())
    ON CONFLICT (sku_id) DO UPDATE SET
      quantity = sku_balances.quantity + EXCLUDED.quantity,
      last_received_at = now();

    v_purchase_count := v_purchase_count + 1;
  END LOOP;

  -- ── 5. Update PO status to reconciled ──
  UPDATE public.purchase_orders
  SET status = 'reconciled',
      expense_id = v_expense_id,
      grand_total = COALESCE((p_payload->>'amount_original')::NUMERIC, 0),
      subtotal = (
        SELECT COALESCE(SUM(pl2.quantity * pl2.price_per_unit), 0)
        FROM public.purchase_logs pl2
        WHERE pl2.expense_id = v_expense_id
      ),
      discount_total = COALESCE((p_payload->>'discount_total')::NUMERIC, 0),
      vat_amount = COALESCE((p_payload->>'vat_amount')::NUMERIC, 0),
      delivery_fee = COALESCE((p_payload->>'delivery_fee')::NUMERIC, 0),
      updated_at = now()
  WHERE id = v_po_id;

  -- ── 6. Update receiving_records status ──
  UPDATE public.receiving_records
  SET status = 'reconciled', expense_id = v_expense_id
  WHERE po_id = v_po_id;

  -- ── 7. Return success ──
  RETURN jsonb_build_object(
    'ok',               true,
    'expense_id',       v_expense_id,
    'purchase_count',   v_purchase_count,
    'sku_auto_created', v_sku_auto_count
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;

COMMENT ON FUNCTION public.fn_approve_po(JSONB)
  IS 'Phase 12: Financial reconciliation by Controller. Creates expense_ledger + purchase_logs + sku_balances from receiving_lines. Reuses SKU resolution and UoM conversion logic from fn_approve_receipt v10.';


-- ─── 4. fn_pending_deliveries ───

CREATE OR REPLACE FUNCTION public.fn_pending_deliveries()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result JSONB;
BEGIN
  SELECT COALESCE(jsonb_agg(po_data ORDER BY po_data->>'expected_date' ASC NULLS LAST), '[]'::jsonb)
  INTO v_result
  FROM (
    SELECT jsonb_build_object(
      'po_id',         po.id,
      'po_number',     po.po_number,
      'supplier_name', s.name,
      'status',        po.status::TEXT,
      'expected_date', po.expected_date,
      'notes',         po.notes,
      'is_overdue',    (po.expected_date IS NOT NULL AND po.expected_date < CURRENT_DATE),
      'line_count',    (SELECT COUNT(*) FROM public.po_lines pl WHERE pl.po_id = po.id),
      'lines',         (
        SELECT COALESCE(jsonb_agg(jsonb_build_object(
          'po_line_id',     pl.id,
          'nomenclature_id', pl.nomenclature_id,
          'sku_id',         pl.sku_id,
          'product_name',   n.name,
          'product_code',   n.product_code,
          'base_unit',      n.base_unit,
          'unit',           pl.unit,
          'qty_ordered',    pl.qty_ordered,
          'qty_already_received', COALESCE(recv.total_received, 0),
          'qty_remaining',  GREATEST(pl.qty_ordered - COALESCE(recv.total_received, 0), 0),
          'barcode',        sk.barcode,
          'brand',          sk.brand
          -- NOTE: No prices returned — /receive screen hides financial data
        ) ORDER BY pl.sort_order), '[]'::jsonb)
        FROM public.po_lines pl
        JOIN public.nomenclature n ON n.id = pl.nomenclature_id
        LEFT JOIN public.sku sk ON sk.id = pl.sku_id
        LEFT JOIN (
          SELECT
            rl.po_line_id,
            SUM(rl.qty_received) AS total_received
          FROM public.receiving_lines rl
          JOIN public.receiving_records rr ON rr.id = rl.receiving_id
          WHERE rr.po_id = po.id
          GROUP BY rl.po_line_id
        ) recv ON recv.po_line_id = pl.id
        WHERE pl.po_id = po.id
      )
    ) AS po_data
    FROM public.purchase_orders po
    JOIN public.suppliers s ON s.id = po.supplier_id
    WHERE po.status IN ('submitted', 'confirmed', 'shipped', 'partially_received')
  ) sub;

  RETURN jsonb_build_object('ok', true, 'deliveries', v_result);

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;

COMMENT ON FUNCTION public.fn_pending_deliveries()
  IS 'Phase 12: Returns pending POs for receiving screen. NO prices — only names, UoM, quantities. Includes already-received aggregation for partial deliveries.';
