-- 225: Customer-channel + order-code + cashier-payment fields for orders (MVP)
-- Project: QR menu (shishka.health) + own order intake alongside Loyverse
-- NOTE: file authored for review — NOT yet applied to the live project.
-- Builds on 022_orders_pipeline.sql (orders, order_items, Realtime).
--
-- MVP scope: pay at the cashier (no online payment provider yet), pickup,
-- our system is the source of truth for website/grab orders.
-- Online-payment tables (payment_transactions) + customer auth are intentionally
-- deferred — see plan "Явно вне MVP".

-- ─── 1. ENUMs ────────────────────────────────────────────────

DO $$ BEGIN
    CREATE TYPE public.payment_status AS ENUM ('unpaid', 'paid', 'refunded');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE public.fulfillment_type AS ENUM ('pickup', 'dine_in');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ─── 2. Extend orders ────────────────────────────────────────
-- Own channel: pickup (+ dine-in QR later). No own delivery → no address columns.
-- order_code is the short human-friendly handle the customer shows at the cashier.

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS order_code       TEXT,
    ADD COLUMN IF NOT EXISTS payment_status   public.payment_status NOT NULL DEFAULT 'unpaid',
    ADD COLUMN IF NOT EXISTS payment_method   TEXT,
    ADD COLUMN IF NOT EXISTS fulfillment_type public.fulfillment_type NOT NULL DEFAULT 'pickup',
    ADD COLUMN IF NOT EXISTS table_number     TEXT,
    ADD COLUMN IF NOT EXISTS channel          TEXT;

COMMENT ON COLUMN public.orders.order_code IS 'Short human-friendly code shown at the cashier, e.g. A-237 (generated by fn_next_order_code, migration 227)';
COMMENT ON COLUMN public.orders.channel    IS 'Own-channel origin: own_web | own_app | grab (DB source enum stays website/syrve/manual)';
COMMENT ON COLUMN public.orders.payment_method IS 'How payment was taken at the cashier: cash | card | promptpay | other (our system is the record, not Loyverse)';

-- Codes reset daily, so uniqueness is enforced only among ACTIVE orders:
-- no two live (new/preparing/ready) orders may share a code at the same time.
-- Delivered/cancelled orders free the code for reuse next day.
CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_active_code
    ON public.orders(order_code)
    WHERE order_code IS NOT NULL AND status IN ('new', 'preparing', 'ready');

CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_channel        ON public.orders(channel) WHERE channel IS NOT NULL;

-- ─── 3. Self-register ────────────────────────────────────────

INSERT INTO migration_log (filename, applied_by, checksum, notes)
VALUES (
  '225_orders_customer_channel.sql',
  'claude-code',
  NULL,
  'Add order_code + payment_status/method + fulfillment_type/table_number + channel to orders (QR menu MVP)'
)
ON CONFLICT DO NOTHING;
