-- QA BUG de58881f — fn_create_purchase_order had no server-side qty validation.
--
-- It inserted qty via COALESCE((v_line->>'qty_ordered')::NUMERIC, 1) with no
-- check that qty > 0, so a direct RPC call could create po_lines with zero or
-- negative qty (corrupting cost/order data). It also inserted the PO header
-- even when the lines array was empty (supplier-only "empty PO").
--
-- FIX:
--   1. Validate the payload BEFORE inserting anything — reject empty/missing
--      lines, reject any line with qty_ordered <= 0 or a missing product.
--      Pre-validating up front means a rejected payload never leaves an orphan
--      PO header (a RETURN after the header INSERT would NOT roll it back).
--   2. CHECK (qty_ordered > 0) on po_lines as a defence-in-depth backstop.
--
-- Validation only — the create/auto-price logic is otherwise unchanged from the
-- live definition. Reversible: restore the prior function body + DROP CONSTRAINT.

CREATE OR REPLACE FUNCTION public.fn_create_purchase_order(p_payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_po_id       UUID;
  v_po_number   TEXT;
  v_line        JSONB;
  v_line_count  INTEGER := 0;
  v_sort        SMALLINT := 0;
  v_unit_price  NUMERIC;
  v_qty         NUMERIC;
BEGIN
  -- ── 1. Validate supplier ──
  IF p_payload->>'supplier_id' IS NULL OR p_payload->>'supplier_id' = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'supplier_id is required');
  END IF;

  -- ── 1b. Validate lines present ──
  IF p_payload->'lines' IS NULL OR jsonb_array_length(p_payload->'lines') = 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'At least one line item is required');
  END IF;

  -- ── 1c. Validate every line BEFORE inserting anything (no orphan header) ──
  FOR v_line IN SELECT * FROM jsonb_array_elements(p_payload->'lines')
  LOOP
    IF (v_line->>'nomenclature_id') IS NULL OR (v_line->>'nomenclature_id') = '' THEN
      RETURN jsonb_build_object('ok', false, 'error', 'Each line item must reference a product');
    END IF;
    v_qty := (v_line->>'qty_ordered')::NUMERIC;
    IF v_qty IS NULL OR v_qty <= 0 THEN
      RETURN jsonb_build_object('ok', false, 'error', 'Quantity must be greater than 0 for every line item');
    END IF;
  END LOOP;

  -- ── 2. INSERT purchase_orders (po_number auto-generated by trigger) ──
  INSERT INTO public.purchase_orders (
    supplier_id,
    expected_date,
    notes,
    created_by
  ) VALUES (
    (p_payload->>'supplier_id')::UUID,
    (p_payload->>'expected_date')::DATE,
    p_payload->>'notes',
    auth.uid()
  )
  RETURNING id, po_number INTO v_po_id, v_po_number;

  -- ── 3. INSERT po_lines (qty already validated > 0) ──
  FOR v_line IN SELECT * FROM jsonb_array_elements(p_payload->'lines')
  LOOP
    v_sort := v_sort + 1;

    -- Auto-populate unit_price from supplier_catalog if not provided
    v_unit_price := (v_line->>'unit_price_expected')::NUMERIC;

    IF v_unit_price IS NULL THEN
      SELECT sc.last_seen_price INTO v_unit_price
      FROM public.supplier_catalog sc
      WHERE sc.supplier_id = (p_payload->>'supplier_id')::UUID
        AND (
          (v_line->>'sku_id' IS NOT NULL AND sc.sku_id = (v_line->>'sku_id')::UUID)
          OR sc.nomenclature_id = (v_line->>'nomenclature_id')::UUID
        )
      ORDER BY
        CASE WHEN sc.sku_id IS NOT NULL THEN 0 ELSE 1 END,
        sc.match_count DESC
      LIMIT 1;
    END IF;

    INSERT INTO public.po_lines (
      po_id, nomenclature_id, sku_id,
      qty_ordered, unit, unit_price_expected,
      sort_order, notes
    ) VALUES (
      v_po_id,
      (v_line->>'nomenclature_id')::UUID,
      CASE WHEN v_line->>'sku_id' IS NOT NULL AND v_line->>'sku_id' <> ''
           THEN (v_line->>'sku_id')::UUID ELSE NULL END,
      (v_line->>'qty_ordered')::NUMERIC,
      COALESCE(v_line->>'unit', 'pcs'),
      v_unit_price,
      v_sort,
      v_line->>'notes'
    );

    v_line_count := v_line_count + 1;
  END LOOP;

  -- ── 4. Return success ──
  RETURN jsonb_build_object(
    'ok',         true,
    'po_id',      v_po_id,
    'po_number',  v_po_number,
    'line_count', v_line_count
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$function$;

-- Defence-in-depth: a po_line can never carry a non-positive quantity.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'po_lines_qty_ordered_positive'
      AND conrelid = 'public.po_lines'::regclass
  ) THEN
    ALTER TABLE public.po_lines
      ADD CONSTRAINT po_lines_qty_ordered_positive CHECK (qty_ordered > 0);
  END IF;
END $$;

INSERT INTO migration_log (filename, applied_by, checksum, notes)
VALUES (
  '324_po_create_qty_validation.sql',
  'claude-code',
  NULL,
  'QA de58881f: fn_create_purchase_order pre-validates lines (reject empty array, qty<=0, missing product) before any INSERT (no orphan header); CHECK (qty_ordered > 0) on po_lines as backstop'
)
ON CONFLICT DO NOTHING;

-- DOWN (manual, for reference):
-- ALTER TABLE public.po_lines DROP CONSTRAINT IF EXISTS po_lines_qty_ordered_positive;
-- (and restore the prior fn_create_purchase_order body)
