-- 384_menu_public_contract.sql
--
-- Codify the contract between this repo and the public menu at shishka.health.
--
-- menu_public, menu_modifiers, site_content and price_tiers are everything the
-- site reads. Until now they existed ONLY in the live database: they appear in
-- none of the migration files and in no file in the shishka-health repo. They
-- were created by hand through the dashboard, so nothing recorded that a schema
-- change here breaks a live customer-facing site, and nobody could rebuild them.
--
-- APPLYING THIS MUST BE A NO-OP. Every statement was generated by reading
-- production (pg_get_viewdef, information_schema.columns, pg_constraint,
-- pg_policies) on 2026-07-28 and is reproduced verbatim. If it errors or changes
-- a row count, that error IS the finding: production differs from what we think.
--
-- Numbering: the highest file here is 374, but production's migration_log has a
-- max of 383 — numbers 375-383 are applied in production with no file in this
-- directory (9 migrations, presumably from unmerged branches). Numbering from the
-- repo max alone would collide with an applied migration, so this takes 384,
-- above both. Per vault/Database/Migrations.md, never reuse a gap.
--
-- Scope is exactly these four objects. Reconciling those 9 missing files is a
-- separate task, and worth doing: they are applied to production and unversioned.
--
-- CONTRACT-REVIEWED: reproduces the live definitions verbatim; no column, filter
-- or policy is added, removed or renamed. contract-check.mjs green before and after.

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- site_content — key/value JSON blocks for hero, CTA, section intros
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.site_content (
  key        text PRIMARY KEY,
  data       jsonb       NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.site_content ADD COLUMN IF NOT EXISTS data       jsonb       NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE public.site_content ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='site_content' AND policyname='site_content_public_read') THEN
    CREATE POLICY site_content_public_read ON public.site_content
      FOR SELECT TO anon, authenticated USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='site_content' AND policyname='site_content_auth_write') THEN
    CREATE POLICY site_content_auth_write ON public.site_content
      FOR ALL TO authenticated USING (true);
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- price_tiers — bundle discount tiers. The site reads only the bundle rows
-- (bundle_dish_code IS NOT NULL AND is_active), but filters on bundle_dish_code
-- without selecting it, so that column must keep existing.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.price_tiers (
  tier_code    text PRIMARY KEY,
  label        text    NOT NULL,
  discount_pct numeric NOT NULL,
  is_active    boolean NOT NULL DEFAULT true,
  sort_order   integer NOT NULL DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.price_tiers ADD COLUMN IF NOT EXISTS category_code          text;
ALTER TABLE public.price_tiers ADD COLUMN IF NOT EXISTS valid_from             date;
ALTER TABLE public.price_tiers ADD COLUMN IF NOT EXISTS valid_to               date;
ALTER TABLE public.price_tiers ADD COLUMN IF NOT EXISTS bundle_dish_code       text;
ALTER TABLE public.price_tiers ADD COLUMN IF NOT EXISTS bundle_manakish_count  integer;
ALTER TABLE public.price_tiers ADD COLUMN IF NOT EXISTS bundle_sauce_count     integer;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='price_tiers_discount_pct_check') THEN
    ALTER TABLE public.price_tiers
      ADD CONSTRAINT price_tiers_discount_pct_check CHECK (discount_pct >= 0 AND discount_pct < 100);
  END IF;
END $$;

ALTER TABLE public.price_tiers ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='price_tiers' AND policyname='price_tiers_read') THEN
    CREATE POLICY price_tiers_read ON public.price_tiers FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='price_tiers' AND policyname='price_tiers_write') THEN
    CREATE POLICY price_tiers_write ON public.price_tiers FOR ALL USING (fn_is_authenticated());
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- menu_public — customer-safe projection of nomenclature.
--
-- NOTE for whoever reads useMenu.js: its header comment claims the row filter is
-- `pos_status = 'synced' AND is_available = true` and that the view is
-- security_invoker. Both are stale. The live filter is is_web_visible, and the
-- view runs with security_invoker = false (owner rights), so the
-- nomenclature_anon_read RLS policy does NOT apply to it — this WHERE clause is
-- the only thing standing between the anon key and a row.
--
-- Exposes no cost column. cost_per_unit is referenced inside bundle_min_price to
-- compute the 60%-margin floor, but the input never leaves the view.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.menu_public AS
 SELECT n.id,
    n.product_code,
    n.name,
    n.customer_short_name,
    n.customer_photo_url,
    n.image_url,
    n.customer_description,
    n.price,
    n.is_available,
    n.is_featured,
    n.pos_status,
    n.calories,
    n.protein,
    n.carbs,
    n.fat,
    n.portion_size,
    n.portion_unit,
    n.category_id,
    n.display_order,
    c.code AS category_code,
    c.name AS category_name,
    c.sort_order AS category_sort_order,
    n.customer_ingredients,
    n.stock_state,
    s.id AS section_id,
    s.name AS section_name,
    s.sort_order AS section_sort_order,
    n.is_web_visible,
    n.web_published_at,
        CASE
            WHEN c.code ~~ 'KP-FIN-MAN%'::text AND n.cost_per_unit > 0::numeric AND n.price > 0::numeric AND ceil(n.cost_per_unit / 0.4) > round(n.price * (( SELECT 1::numeric - max(pt.discount_pct) / 100.0
               FROM price_tiers pt
              WHERE pt.bundle_dish_code IS NOT NULL AND pt.is_active))) THEN ceil(n.cost_per_unit / 0.4)::integer
            ELSE NULL::integer
        END AS bundle_min_price
   FROM nomenclature n
     LEFT JOIN product_categories c ON c.id = n.category_id
     LEFT JOIN product_categories s ON s.id =
        CASE
            WHEN c.is_menu_section THEN c.id
            ELSE c.parent_id
        END
  WHERE n.product_code ~~ 'SALE-%'::text AND n.is_web_visible = true AND COALESCE(n.is_deleted, false) = false AND (n.name IS NULL OR n.name !~~* '[ARCHIVED]%'::text);

-- ─────────────────────────────────────────────────────────────────────────────
-- menu_modifiers — Loyverse-backed builder options, nutrition scaled per portion.
-- This is where pos_status = 'synced' AND is_available = true actually lives.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.menu_modifiers AS
 SELECT o.dish_id,
    o.loyverse_modifier_list_name AS group_name,
    g.sort_order AS group_sort,
    COALESCE(m.customer_short_name, m.name) AS option_name,
    m.emoji AS option_emoji,
    o.price_delta,
    o.is_default,
    o.sort_order,
    m.stock_state AS option_stock_state,
    g.min_select AS group_min_select,
    g.max_select AS group_max_select,
    round(m.calories::numeric * COALESCE(o.quantity_per_unit, 1::numeric))::integer AS calories,
    round(m.protein * COALESCE(o.quantity_per_unit, 1::numeric), 1) AS protein,
    round(m.carbs * COALESCE(o.quantity_per_unit, 1::numeric), 1) AS carbs,
    round(m.fat * COALESCE(o.quantity_per_unit, 1::numeric), 1) AS fat
   FROM nomenclature_modifier_options o
     JOIN nomenclature m ON m.id = o.modifier_id
     LEFT JOIN dish_modifier_groups g ON g.dish_id = o.dish_id AND g.loyverse_modifier_list_id = o.loyverse_modifier_list_id
  WHERE (o.dish_id IN ( SELECT nomenclature.id
           FROM nomenclature
          WHERE nomenclature.product_code ~~ 'SALE-%'::text AND nomenclature.pos_status = 'synced'::pos_status_enum AND nomenclature.is_available = true));

-- Reads the site depends on. Deliberately SELECT only: the write grants anon
-- currently holds on these objects are inert (both views are non-updatable with
-- no INSTEAD OF triggers) but should be revoked separately — see the follow-up
-- note in the PR. Revoking here would stop this migration being a no-op.
GRANT SELECT ON public.menu_public       TO anon, authenticated;
GRANT SELECT ON public.menu_modifiers    TO anon, authenticated;
GRANT SELECT ON public.site_content      TO anon, authenticated;
GRANT SELECT ON public.price_tiers       TO anon, authenticated;
GRANT SELECT ON public.nomenclature_tags TO anon, authenticated;
GRANT SELECT ON public.tags              TO anon, authenticated;

INSERT INTO migration_log (filename, applied_by, checksum, notes)
VALUES (
  '384_menu_public_contract.sql',
  'claude-code',
  NULL,
  'Codify the shishka.health menu contract (menu_public, menu_modifiers, site_content, price_tiers) verbatim from production — no-op by construction'
)
ON CONFLICT DO NOTHING;

COMMIT;
