import { getSupabase } from "../lib/supabase.js";
import { execSync } from "child_process";
import { writeFileSync } from "fs";
import { resolve } from "path";

/**
 * generate_status — HC-1 Reactive Status
 *
 * Generates STATUS.md from Supabase MC tasks + git state.
 * Called automatically via post-commit hook.
 * Manual editing of STATUS.md is PROHIBITED.
 */

interface TaskSummary {
  status: string;
  count: number;
  tasks: Array<{
    id: string;
    title: string;
    domain: string;
    priority: string;
    assigned_to: string | null;
  }>;
}

function gitCommand(cmd: string): string {
  try {
    return execSync(cmd, { encoding: "utf-8", timeout: 5000 }).trim();
  } catch {
    return "(unavailable)";
  }
}

export async function generateStatus(args: { repo_root?: string }) {
  const sb = getSupabase();

  // 1. Query MC tasks grouped by status
  const { data: tasks, error } = await sb
    .from("business_tasks")
    .select("id, title, domain, status, priority, assigned_to, executor_type, due_date, tags, related_ids, updated_at")
    .not("status", "in", '("cancelled")')
    .order("updated_at", { ascending: false })
    .limit(100);

  if (error) {
    return { error: `DB error: ${error.message}` };
  }

  const allTasks = tasks ?? [];

  // Group by status
  const statusGroups: Record<string, TaskSummary> = {};
  const statusOrder = ["in_progress", "blocked", "inbox", "backlog", "done"];

  for (const status of statusOrder) {
    const filtered = allTasks.filter((t) => t.status === status);
    statusGroups[status] = {
      status,
      count: filtered.length,
      tasks: filtered.slice(0, 10).map((t) => ({
        id: t.id,
        title: t.title,
        domain: t.domain,
        priority: t.priority,
        assigned_to: t.assigned_to,
      })),
    };
  }

  // 2. Git state
  const branch = gitCommand("git branch --show-current");
  const recentCommits = gitCommand("git log --oneline -5");
  const latestTag = gitCommand("git describe --tags --abbrev=0 2>/dev/null || echo '(no tags)'");

  // 3. Migration state
  const { data: migrationData } = await sb
    .from("migration_log")
    .select("version, name, status, applied_at")
    .order("version", { ascending: false })
    .limit(1);

  const latestMigration = migrationData?.[0] ?? null;

  // 4. Build STATUS.md content
  const now = new Date().toISOString().split("T")[0];
  const inProgress = statusGroups["in_progress"];
  const blocked = statusGroups["blocked"];
  const inbox = statusGroups["inbox"];
  const backlog = statusGroups["backlog"];
  const done = statusGroups["done"];

  const lines: string[] = [
    "# Global Deployment State",
    "",
    `> **Auto-generated by \`generate_status\` on ${now}. DO NOT EDIT MANUALLY (HC-1).**`,
    "",
    `**Database:** Supabase PostgreSQL 17.6 (ap-south-1)`,
    latestMigration
      ? `**Latest migration:** ${latestMigration.version} — ${latestMigration.name} (${latestMigration.status}, ${latestMigration.applied_at?.split("T")[0] ?? "unknown"})`
      : `**Latest migration:** unknown`,
    `**Active branch:** \`${branch}\``,
    `**Generated:** ${now}`,
    "",
    "## Active Work (in_progress)",
    "",
  ];

  if (inProgress.count === 0) {
    lines.push("No tasks in progress.");
  } else {
    lines.push("| Task | Domain | Priority | Assigned |");
    lines.push("|------|--------|----------|----------|");
    for (const t of inProgress.tasks) {
      lines.push(`| ${t.title} | ${t.domain} | ${t.priority} | ${t.assigned_to ?? "—"} |`);
    }
  }

  lines.push("");

  if (blocked.count > 0) {
    lines.push("## Blocked");
    lines.push("");
    lines.push("| Task | Domain | Priority |");
    lines.push("|------|--------|----------|");
    for (const t of blocked.tasks) {
      lines.push(`| ${t.title} | ${t.domain} | ${t.priority} |`);
    }
    lines.push("");
  }

  if (inbox.count > 0) {
    lines.push(`## Inbox (${inbox.count} tasks awaiting triage)`);
    lines.push("");
    lines.push("| Task | Domain | Priority |");
    lines.push("|------|--------|----------|");
    for (const t of inbox.tasks) {
      lines.push(`| ${t.title} | ${t.domain} | ${t.priority} |`);
    }
    lines.push("");
  }

  lines.push(`## Summary`);
  lines.push("");
  lines.push(`| Status | Count |`);
  lines.push(`|--------|-------|`);
  for (const status of statusOrder) {
    lines.push(`| ${status} | ${statusGroups[status].count} |`);
  }
  lines.push("");

  lines.push("## Recent Commits");
  lines.push("");
  lines.push("```");
  lines.push(recentCommits);
  lines.push("```");
  lines.push("");

  const markdown = lines.join("\n");

  // 5. Write to STATUS.md if repo_root provided
  if (args.repo_root) {
    const statusPath = resolve(args.repo_root, "STATUS.md");
    writeFileSync(statusPath, markdown, "utf-8");
    return {
      success: true,
      wrote_to: statusPath,
      summary: {
        in_progress: inProgress.count,
        blocked: blocked.count,
        inbox: inbox.count,
        backlog: backlog.count,
        done: done.count,
        total: allTasks.length,
      },
    };
  }

  // If no repo_root, return markdown as text
  return {
    success: true,
    markdown,
    summary: {
      in_progress: inProgress.count,
      blocked: blocked.count,
      inbox: inbox.count,
      backlog: backlog.count,
      done: done.count,
      total: allTasks.length,
    },
  };
}
