import { getSupabase, getSupabaseOptional } from "../lib/supabase.js";
import { SupabaseClient } from "@supabase/supabase-js";
import { execSync } from "child_process";
import { writeFileSync } from "fs";
import { resolve } from "path";

/**
 * generate_status — HC-1 Reactive Status
 *
 * Generates STATUS.md from Supabase MC tasks + git state.
 * Called automatically via post-commit hook.
 * Manual editing of STATUS.md is PROHIBITED.
 */

interface TaskSummary {
  status: string;
  count: number;
  tasks: Array<{
    id: string;
    title: string;
    domain: string;
    priority: string;
    assigned_to: string | null;
  }>;
}

interface McSnapshot {
  allTasks: Array<{
    id: string;
    title: string;
    domain: string;
    status: string;
    priority: string;
    assigned_to: string | null;
    [k: string]: unknown;
  }>;
  latestMigration: { version: string; name: string; status: string; applied_at: string | null } | null;
  offlineReason: string | null;
}

interface GitState {
  branch: string;
  recentCommits: string;
  latestTag: string;
}

function gitCommand(cmd: string): string {
  try {
    return execSync(cmd, { encoding: "utf-8", timeout: 5000 }).trim();
  } catch {
    return "(unavailable)";
  }
}

async function fetchMcSnapshot(sb: SupabaseClient | null, allowOffline: boolean): Promise<McSnapshot> {
  if (!sb) {
    return {
      allTasks: [],
      latestMigration: null,
      offlineReason: "Supabase credentials not available (SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY missing)",
    };
  }

  const { data: tasks, error } = await sb
    .from("business_tasks")
    .select("id, title, domain, status, priority, assigned_to, executor_type, due_date, tags, related_ids, updated_at")
    .not("status", "in", '("cancelled")')
    .order("updated_at", { ascending: false })
    .limit(100);

  if (error) {
    if (!allowOffline) {
      throw new Error(`DB error: ${error.message}`);
    }
    console.warn(`[generate-status] DB query failed, degrading to git-only: ${error.message}`);
    return { allTasks: [], latestMigration: null, offlineReason: `DB query failed: ${error.message}` };
  }

  const { data: migrationData } = await sb
    .from("migration_log")
    .select("version, name, status, applied_at")
    .order("version", { ascending: false })
    .limit(1);

  return { allTasks: tasks ?? [], latestMigration: migrationData?.[0] ?? null, offlineReason: null };
}

function collectGitState(): GitState {
  return {
    branch: gitCommand("git branch --show-current"),
    recentCommits: gitCommand("git log --oneline -5"),
    latestTag: gitCommand("git describe --tags --abbrev=0 2>/dev/null || echo '(no tags)'"),
  };
}

function renderTaskSection(heading: string, group: TaskSummary): string[] {
  if (group.count === 0) return [];
  const lines = [`## ${heading}`, "", "| Task | Domain | Priority |", "|------|--------|----------|"];
  for (const t of group.tasks) {
    lines.push(`| ${t.title} | ${t.domain} | ${t.priority} |`);
  }
  lines.push("");
  return lines;
}

function renderStatusMarkdown(
  mc: McSnapshot,
  git: GitState,
): { markdown: string; summary: Record<string, number> & { total: number } } {
  const statusOrder = ["in_progress", "blocked", "inbox", "backlog", "done"];
  const statusGroups: Record<string, TaskSummary> = {};

  for (const status of statusOrder) {
    const filtered = mc.allTasks.filter((t) => t.status === status);
    statusGroups[status] = {
      status,
      count: filtered.length,
      tasks: filtered.slice(0, 10).map((t) => ({
        id: t.id,
        title: t.title,
        domain: t.domain,
        priority: t.priority,
        assigned_to: t.assigned_to,
      })),
    };
  }

  const now = new Date().toISOString().split("T")[0];
  const inProgress = statusGroups["in_progress"];
  const blocked = statusGroups["blocked"];
  const inbox = statusGroups["inbox"];

  const lines: string[] = [
    "# Global Deployment State",
    "",
    `> **Auto-generated by \`generate_status\` on ${now}. DO NOT EDIT MANUALLY (HC-1).**`,
    "",
  ];

  if (mc.offlineReason) {
    lines.push(
      `> ⚠ **MC data stale — git-only refresh.** Reason: ${mc.offlineReason}. Task tables below may be outdated; re-run with Supabase credentials to refresh.`,
      "",
    );
  }

  lines.push(
    `**Database:** Supabase PostgreSQL 17.6 (ap-south-1)`,
    mc.latestMigration
      ? `**Latest migration:** ${mc.latestMigration.version} — ${mc.latestMigration.name} (${mc.latestMigration.status}, ${mc.latestMigration.applied_at?.split("T")[0] ?? "unknown"})`
      : `**Latest migration:** ${mc.offlineReason ? "unknown (offline)" : "unknown"}`,
    `**Active branch:** \`${git.branch}\``,
    `**Generated:** ${now}`,
    "",
    "## Active Work (in_progress)",
    "",
  );

  if (mc.offlineReason) {
    lines.push("_MC task tables unavailable in offline mode._", "");
  } else {
    if (inProgress.count === 0) {
      lines.push("No tasks in progress.");
    } else {
      lines.push("| Task | Domain | Priority | Assigned |", "|------|--------|----------|----------|");
      for (const t of inProgress.tasks) {
        lines.push(`| ${t.title} | ${t.domain} | ${t.priority} | ${t.assigned_to ?? "—"} |`);
      }
    }
    lines.push("");
    lines.push(...renderTaskSection("Blocked", blocked));
    lines.push(...renderTaskSection(`Inbox (${inbox.count} tasks awaiting triage)`, inbox));
    lines.push("## Summary", "", "| Status | Count |", "|--------|-------|");
    for (const status of statusOrder) {
      lines.push(`| ${status} | ${statusGroups[status].count} |`);
    }
    lines.push("");
  }

  lines.push("## Recent Commits", "", "```", git.recentCommits, "```", "");

  return {
    markdown: lines.join("\n"),
    summary: {
      in_progress: inProgress.count,
      blocked: blocked.count,
      inbox: inbox.count,
      backlog: statusGroups["backlog"].count,
      done: statusGroups["done"].count,
      total: mc.allTasks.length,
    },
  };
}

export async function generateStatus(args: {
  repo_root?: string;
  /**
   * When true, missing Supabase credentials or DB errors degrade gracefully:
   * STATUS.md is still written using git-only state and an offline banner,
   * instead of failing. Used by the post-commit hook on dev machines without
   * a local .env. Default: false (strict mode for explicit tool calls).
   */
  allow_offline?: boolean;
}) {
  const allowOffline = args.allow_offline ?? false;
  const sb = allowOffline ? getSupabaseOptional() : getSupabase();

  let mc: McSnapshot;
  try {
    mc = await fetchMcSnapshot(sb, allowOffline);
  } catch (err: unknown) {
    return { error: (err as Error).message };
  }

  const git = collectGitState();
  const { markdown, summary } = renderStatusMarkdown(mc, git);

  if (args.repo_root) {
    const statusPath = resolve(args.repo_root, "STATUS.md");
    writeFileSync(statusPath, markdown, "utf-8");
    return { success: true, wrote_to: statusPath, summary };
  }

  return { success: true, markdown, summary };
}
